image: Visual Studio 2019

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - source/
    - vcproj/
    - appveyor.yml

install:
  - cmd : vcpkg install wxwidgets:x64-windows
  - cmd : vcpkg install boost:x64-windows
  - cmd : vcpkg install libarchive:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: vcproj\**\theforgottenserver*.exe
  - path: vcproj\**\*.dll